export const ACCOUNT_TYPES = {
  PERSON: 'person',
  CASH: 'cash',
  BANK: 'bank',
  EXPENSE: 'expense',
  ASSET: 'asset',
  PROJECT: 'project',
  SUMMARY: 'summary',
  REVIEW: 'review',
}

export const ACCOUNT_STATUSES = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  NEEDS_REVIEW: 'needs_review',
}

export const VALUE_KINDS = {
  CASH: 'cash',
  BANK: 'bank',
  RECEIVABLE: 'receivable',
  EXPENSE: 'expense',
  ASSET: 'asset',
  SUMMARY: 'summary',
  REVIEW: 'review',
}

function account({
  id,
  legacyName,
  ownerName,
  subAccountName,
  type,
  valueKind,
  openingDinar = 0,
  openingUsd = 0,
  status = ACCOUNT_STATUSES.ACTIVE,
  notes = '',
}) {
  return {
    id,
    legacyName,
    ownerName,
    subAccountName,
    type,
    valueKind,
    openingDinar,
    openingUsd,
    status,
    notes,
    createdFrom: 'numbers_table_1',
  }
}

export const mohammadAccountCatalog = [
  account({
    id: 'me-cash',
    legacyName: 'اني ✅',
    ownerName: 'أنا',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.CASH,
    valueKind: VALUE_KINDS.CASH,
    openingDinar: 47164.675,
    openingUsd: 0.220779220779,
    notes: 'الرصيد الرئيسي الحالي، ويشمل أثر البطاقات التاريخي.',
  }),
  account({
    id: 'me-jumhouria',
    legacyName: 'حسابي الجمهورية',
    ownerName: 'أنا',
    subAccountName: 'الجمهورية',
    type: ACCOUNT_TYPES.BANK,
    valueKind: VALUE_KINDS.BANK,
    openingDinar: -27290,
  }),
  account({
    id: 'saeed-cash',
    legacyName: 'سعيد انغ',
    ownerName: 'سعيد',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    openingDinar: 18260,
  }),
  account({
    id: 'saeed-bank',
    legacyName: 'سعيد انغ مصرف ☂️',
    ownerName: 'سعيد',
    subAccountName: 'مصرفي',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    openingDinar: 13569.9988900001,
    notes: 'فرع مصرفي لشخص، وليس مكان مال خاص بي.',
  }),
  account({
    id: 'saif-cash',
    legacyName: 'سيف',
    ownerName: 'سيف',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    openingDinar: 3.63,
  }),
  account({
    id: 'rabee-cash',
    legacyName: 'ربيع',
    ownerName: 'ربيع',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    openingDinar: -24942.2,
  }),
  account({
    id: 'aneer-aman-group',
    legacyName: 'انير قروب الامان',
    ownerName: 'انير قروب الأمان',
    subAccountName: 'حساب',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'mohammad-sweibgh',
    legacyName: 'محمد السويبغ',
    ownerName: 'محمد السويبغ',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    openingDinar: 9745,
  }),
  account({
    id: 'mother-account',
    legacyName: 'حساب امي',
    ownerName: 'أمي',
    subAccountName: 'حساب',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'dania-account',
    legacyName: 'حساب دانيا',
    ownerName: 'دانيا',
    subAccountName: 'حساب',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    openingDinar: -2600,
  }),
  account({
    id: 'souf-bin-issa',
    legacyName: 'سوف بن عيسي',
    ownerName: 'سوف بن عيسى',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    openingDinar: 250,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
    notes: 'تأكيد الاسم مطلوب.',
  }),
  account({
    id: 'masna-alheira',
    legacyName: 'مصنع الهيرة',
    ownerName: 'مصنع الهيرة',
    subAccountName: 'حساب',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'wadi-alrabee',
    legacyName: 'وادي الربيع',
    ownerName: 'وادي الربيع',
    subAccountName: 'حساب',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'sorman',
    legacyName: 'صرمان',
    ownerName: 'صرمان',
    subAccountName: 'حساب',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'aziziya',
    legacyName: 'العزيزية',
    ownerName: 'العزيزية',
    subAccountName: 'حساب',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'hararat',
    legacyName: 'الحرارات',
    ownerName: 'الحرارات',
    subAccountName: 'حساب',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'zahra',
    legacyName: 'الزهراء',
    ownerName: 'الزهراء',
    subAccountName: 'حساب',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'ali-forsa',
    legacyName: 'علي فرصة',
    ownerName: 'علي فرصة',
    subAccountName: 'حساب',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'omar-gold',
    legacyName: 'عمر الذهب',
    ownerName: 'عمر الذهب',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    openingDinar: 24500,
  }),
  account({
    id: 'bassam',
    legacyName: 'بسام',
    ownerName: 'بسام',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'office-settlement',
    legacyName: 'مصاريف مقر',
    ownerName: 'المقر',
    subAccountName: 'حساب تسوية',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    openingDinar: 4365,
    notes: 'يعامل كجهة/شخص لأنه قد يدفع لاحقًا، وليس كمصروف نهائي.',
  }),
  account({
    id: 'mohammad-doghari-naluti',
    legacyName: 'محمد الدوغاري نالوتي',
    ownerName: 'محمد الدوغاري نالوتي',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    openingDinar: 10400,
  }),
  account({
    id: 'mohammad-qarada',
    legacyName: 'محمد قرادة',
    ownerName: 'محمد قرادة',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'hatem-fitouri',
    legacyName: 'حاتم الفيتوري',
    ownerName: 'حاتم الفيتوري',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'aymen-krar',
    legacyName: 'ايمن كرير',
    ownerName: 'أيمن كرير',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'issam-masri',
    legacyName: 'عصام المصري',
    ownerName: 'عصام المصري',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'saeed-cards-legacy',
    legacyName: 'سعيد انغ بطاقات 🪪',
    ownerName: 'سعيد',
    subAccountName: 'بطاقات تاريخي',
    type: ACCOUNT_TYPES.REVIEW,
    valueKind: VALUE_KINDS.REVIEW,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
    notes: 'حساب بطاقات قديم؛ لا يستخدم في المرحلة الأولى إلا بعد قرار.',
  }),
  account({
    id: 'issa-sounsi',
    legacyName: 'عيسي السونسي',
    ownerName: 'عيسى السونسي',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    openingDinar: 2000,
  }),
  account({
    id: 'saif-2',
    legacyName: 'سيف 2',
    ownerName: 'سيف',
    subAccountName: 'حساب ثاني',
    type: ACCOUNT_TYPES.REVIEW,
    valueKind: VALUE_KINDS.REVIEW,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
    notes: 'هل هو نفس سيف أم حساب مستقل؟',
  }),
  account({
    id: 'rabee-jumhouria',
    legacyName: 'ربيع الجمهورية 🏦 ',
    ownerName: 'ربيع',
    subAccountName: 'الجمهورية',
    type: ACCOUNT_TYPES.BANK,
    valueKind: VALUE_KINDS.BANK,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
  }),
  account({
    id: 'rabee-wahda',
    legacyName: 'ربيع الوحدة🐢',
    ownerName: 'ربيع',
    subAccountName: 'الوحدة',
    type: ACCOUNT_TYPES.BANK,
    valueKind: VALUE_KINDS.BANK,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
  }),
  account({
    id: 'north-africa',
    legacyName: 'شمال افريقيا',
    ownerName: 'غير محدد',
    subAccountName: 'شمال أفريقيا',
    type: ACCOUNT_TYPES.REVIEW,
    valueKind: VALUE_KINDS.REVIEW,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
    notes: 'هل هو حساب مصرفي لك أم لشخص؟',
  }),
  account({
    id: 'rabee-turkey',
    legacyName: 'ربيع 🇹🇷',
    ownerName: 'ربيع',
    subAccountName: 'تركيا',
    type: ACCOUNT_TYPES.BANK,
    valueKind: VALUE_KINDS.BANK,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
  }),
  account({
    id: 'saeed-turkey',
    legacyName: 'سعيد انغ 🇹🇷',
    ownerName: 'سعيد',
    subAccountName: 'تركيا',
    type: ACCOUNT_TYPES.BANK,
    valueKind: VALUE_KINDS.BANK,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
  }),
  account({
    id: 'father-account',
    legacyName: 'حساب بوي ',
    ownerName: 'أبي',
    subAccountName: 'حساب',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
  }),
  account({
    id: 'amhammad-bozrara',
    legacyName: 'امحمد بوزرارة',
    ownerName: 'امحمد بوزرارة',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
  }),
  account({
    id: 'rustam-khaneb',
    legacyName: 'رستم الخانب',
    ownerName: 'رستم الخانب',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'abualgasem-obaideen',
    legacyName: 'ابوالقاسم عبيدين',
    ownerName: 'أبوالقاسم عبيدين',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'ads-for-sale',
    legacyName: 'اعلام للبيع',
    ownerName: 'إعلام للبيع',
    subAccountName: 'أصل/نشاط',
    type: ACCOUNT_TYPES.ASSET,
    valueKind: VALUE_KINDS.ASSET,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
    notes: 'هل هو أصل أم نشاط بيع؟',
  }),
  account({
    id: 'issues',
    legacyName: 'مشاكل',
    ownerName: 'مشاكل',
    subAccountName: 'تصحيح/تكلفة',
    type: ACCOUNT_TYPES.REVIEW,
    valueKind: VALUE_KINDS.REVIEW,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
  }),
  account({
    id: 'tareq-ang',
    legacyName: 'طارق انغ',
    ownerName: 'طارق',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
  }),
  account({
    id: 'nizar',
    legacyName: 'نزار',
    ownerName: 'نزار',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'murad',
    legacyName: 'مراد',
    ownerName: 'مراد',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'samer-harran',
    legacyName: 'سامر الحران',
    ownerName: 'سامر الحران',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'omar-bgar',
    legacyName: 'عمر بقر',
    ownerName: 'عمر بقر',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'saeed-keshlaf',
    legacyName: 'سعيد كشلاف',
    ownerName: 'سعيد كشلاف',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'bilal',
    legacyName: 'بلال',
    ownerName: 'بلال',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'waleed-saloua',
    legacyName: 'وليد الصلوعة',
    ownerName: 'وليد الصلوعة',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'abdo-naluti',
    legacyName: 'عبدو نالوتي',
    ownerName: 'عبدو نالوتي',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    openingDinar: 500,
  }),
  account({
    id: 'aymen-gargit',
    legacyName: 'ايمن القرقيط',
    ownerName: 'أيمن القرقيط',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
  }),
  account({
    id: 'trump',
    legacyName: 'ترامب',
    ownerName: 'ترامب',
    subAccountName: 'حساب/أصل',
    type: ACCOUNT_TYPES.REVIEW,
    valueKind: VALUE_KINDS.REVIEW,
    openingDinar: 4000,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
  }),
  account({
    id: 'gun',
    legacyName: 'مسدس',
    ownerName: 'مسدس',
    subAccountName: 'أصل',
    type: ACCOUNT_TYPES.ASSET,
    valueKind: VALUE_KINDS.ASSET,
    openingDinar: 1500,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
    notes: 'تأكيد أنه أصل.',
  }),
  account({
    id: 'games-asset',
    legacyName: 'العاب',
    ownerName: 'ألعاب',
    subAccountName: 'أصل',
    type: ACCOUNT_TYPES.ASSET,
    valueKind: VALUE_KINDS.ASSET,
    openingDinar: 15550,
  }),
  account({
    id: 'land-asset',
    legacyName: 'قطعة ارض',
    ownerName: 'قطعة أرض',
    subAccountName: 'أصل',
    type: ACCOUNT_TYPES.ASSET,
    valueKind: VALUE_KINDS.ASSET,
    openingDinar: 16700,
  }),
  account({
    id: 'new-truck-asset',
    legacyName: 'شاحنة جديدة',
    ownerName: 'الشاحنات',
    subAccountName: 'أصل',
    type: ACCOUNT_TYPES.ASSET,
    valueKind: VALUE_KINDS.ASSET,
    openingDinar: 222500,
  }),
  account({
    id: 'personal-expense',
    legacyName: 'مصروف',
    ownerName: 'أنا',
    subAccountName: 'مصروف شخصي',
    type: ACCOUNT_TYPES.EXPENSE,
    valueKind: VALUE_KINDS.EXPENSE,
    openingDinar: 112240,
  }),
]

export const mohammadSummaryAccounts = [
  account({
    id: 'trucks-expense-summary',
    legacyName: 'الشاحنات مصروف',
    ownerName: 'الشاحنات',
    subAccountName: 'مصاريف موحدة',
    type: ACCOUNT_TYPES.SUMMARY,
    valueKind: VALUE_KINDS.SUMMARY,
    openingDinar: 122595,
    notes: 'ملخص تقريري، لا يستخدم كطرف حركة عادي.',
  }),
  account({
    id: 'trucks-income-summary',
    legacyName: 'الشاحنات مكاسب',
    ownerName: 'الشاحنات',
    subAccountName: 'مكاسب موحدة',
    type: ACCOUNT_TYPES.SUMMARY,
    valueKind: VALUE_KINDS.SUMMARY,
    openingDinar: 344635,
    notes: 'ملخص تقريري، لا يستخدم كطرف حركة عادي.',
  }),
  account({
    id: 'truck-2-income-summary',
    legacyName: 'مكاسب شاحنة 2',
    ownerName: 'الشاحنات',
    subAccountName: 'مكاسب شاحنة 2 تاريخي',
    type: ACCOUNT_TYPES.SUMMARY,
    valueKind: VALUE_KINDS.SUMMARY,
    openingDinar: 220370,
  }),
  account({
    id: 'truck-2-expense-summary',
    legacyName: 'مصاريف شاحنة 2',
    ownerName: 'الشاحنات',
    subAccountName: 'مصاريف شاحنة 2 تاريخي',
    type: ACCOUNT_TYPES.SUMMARY,
    valueKind: VALUE_KINDS.SUMMARY,
    openingDinar: 60380,
  }),
  account({
    id: 'truck-1-income-summary',
    legacyName: 'مكاسب من الشاحنة',
    ownerName: 'الشاحنات',
    subAccountName: 'مكاسب شاحنة تاريخي',
    type: ACCOUNT_TYPES.SUMMARY,
    valueKind: VALUE_KINDS.SUMMARY,
    openingDinar: 124265,
  }),
  account({
    id: 'truck-1-expense-summary',
    legacyName: 'مصاريف شاحنة',
    ownerName: 'الشاحنات',
    subAccountName: 'مصاريف شاحنة تاريخي',
    type: ACCOUNT_TYPES.SUMMARY,
    valueKind: VALUE_KINDS.SUMMARY,
    openingDinar: 62215,
  }),
]

export const knownExternalAccounts = [
  account({
    id: 'mohammad-keifo',
    legacyName: 'محمد الكيفو',
    ownerName: 'محمد الكيفو',
    subAccountName: 'كاش',
    type: ACCOUNT_TYPES.PERSON,
    valueKind: VALUE_KINDS.RECEIVABLE,
    status: ACCOUNT_STATUSES.NEEDS_REVIEW,
    notes: 'ظهر في حركة من Actions ولم يكن موجودًا في Table 1.',
  }),
]

export function buildAccountMap(accounts = mohammadAccountCatalog) {
  return new Map(accounts.map((accountItem) => [accountItem.id, accountItem]))
}

export function getActivePostingAccounts(accounts = mohammadAccountCatalog) {
  return accounts.filter(
    (accountItem) =>
      accountItem.status === ACCOUNT_STATUSES.ACTIVE && accountItem.type !== ACCOUNT_TYPES.SUMMARY,
  )
}
